server:
  port: 50005
spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  sleuth:
    annotation:
      enabled: true
  data:
    mongodb:
      database: flights
      host: mongo

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}



