spring:
  profiles: docker

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
  statusPageUrlPath: /actuator/info
  healthCheckUrlPath: /actuator
  instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
logging:
  level:
    com.netflix.discovery: 'ON'
    org.springframework.cloud.gateway: 'TRACE'
