server:
  port: 8888
  name: edge

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  sleuth:
    annotation:
      enabled: true

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

eureka:
  instance:
      preferIpAddress: true
      leaseRenewalIntervalInSeconds: 10
  client:
    fetchRegistry: true
    registerWithEureka: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG

management:
  security:
    enabled: false
  health:
    defaults: true
    sensitive: true
  endpoints:
    web:
      expose: "*"
    health:
      show-details: true
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST

zuul:
  routes:
    image_recognition:
      path: /api/v1/image_recognition/**
      sensitiveHeaders:
      serviceId: image_recognition
    authorization:
      path: /api/v1/authorization/**
      sensitiveHeaders:
      serviceId: authorization
  host:
    connectTimeoutMillis: 3000
    socketTimeoutMillis: 3000
